import '@/styles/globals.css';
import { NextUIProvider } from '@nextui-org/react';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (<>
    <Head>
        <title>NakanoWeb制作Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
    <NextUIProvider>
      <Component {...pageProps} />
      </NextUIProvider>
  </>
  )
}



